# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install imagemagik
      run: sudo apt-get install -qy pkg-config imagemagick libmagickwand-dev libmagickcore-dev 

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        # go get gopkg.in/gographics/imagick.v2/imagick
        CGO_ENABLED=1 CGO_CFLAGS="$(pkg-config --cflags MagickWand)" CGO_LDFLAGS="$(pkg-config --libs MagickWand)" go build -v ./...

    - name: Test
      run: go test -v ./...
